version: '3'
services:
  master:
    image: centos:7.9.2009
    stdin_open: true
    tty: true
    networks:
      - net
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24